config/routes.rb
Rails.application.routes.draw do

  resources :subjects  do
    get :subject_teacher_list,on: :collection
    get :assign_teachers,on: :collection
    post :create_teachers_subject,on: :collection
  end	
  resources :students do 
    post :student_mark_create,on: :collection
    get :mark_form, on: :collection
  end  
  root :to => "sessions#new"
  resources :users
  resources :sessions, only: [:new, :create, :destroy] 
  get "login", to: 'sessions#new', as: 'login'
  get "logout", to: 'sessions#destroy', as: 'logout'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
	has_many :student_marks
	validates :name, presence: true
	validates :student_id, presence: true,uniqueness: true

	def self.calculate_rank
    total = ""
		rank = ""
		Student.all.order(total: :desc).each_with_index do |student,index|
		  if student.total == total
		    rank = rank
		  else
		    rank = index+1
		  end  
		  student.update(rank: rank)
		  total = student.total  
		end
	end	
	
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all.order(rank: :asc)
    @subjects = Subject.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def mark_form
    @students = Student.all
    @teacher = current_user
    @student_mark = StudentMark.new
    @subject = current_user.user_subject.subject
  end

  def student_mark_create
    student_id = student_mark_params[:student_id]
    mark = student_mark_params[:mark]
    student_mark_ids = student_mark_params[:id]
    student_id.each_with_index do |stud_id,index|
      if student_mark_ids[index] == ""
        StudentMark.create(student_id: stud_id,mark: mark[index],subject_id: current_user.user_subject.subject.id)
      else
        StudentMark.find(student_mark_ids[index]).update(mark: mark[index])
      end  
    end
    Student.calculate_rank
    redirect_to students_url  
  end  
  
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :student_id, :status)
    end

    def student_mark_params
      params.require(:student_mark).permit(id: [], student_id: [], mark: [])
    end
end

app/helpers/students_helper.rb
module StudentsHelper
  
  def student_mark(student_id,subject_id)
    StudentMark.where(student_id: student_id,subject_id: subject_id).present? ? StudentMark.find_by(student_id: student_id,subject_id: subject_id).mark : "" 
  end	

  def student_mark_id(student_id,subject_id)
    StudentMark.where(student_id: student_id,subject_id: subject_id).present? ? StudentMark.find_by(student_id: student_id,subject_id: subject_id).id : "" 
  end	

end

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :student_name %>
  </div>

  <div class="field">
    <%= form.label :student_id, "Student ID" %>
    <%= form.text_field :student_id, id: :student_student_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table border="2">
  <thead>
    <tr>
      <th>Name</th>
      <th>Student</th>
      <%if check_admin(current_user.role_id)%>
        <%@subjects.map do |subject|%>
          <th><%= subject.name%></th>
        <%end%>
        <th>Total</th>
        <th>Rank</th>
        <th colspan="3">Actions</th>  
      <%else%>
        <%if current_user.user_subject.present?%>
          <%subject_id = current_user.user_subject.subject.id%>
          <th><%= current_user.user_subject.subject.name%></th>
        <%end%>
      <%end%>    
      
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.student_id %></td>
        <%if check_admin(current_user.role_id)%>
          <%@subjects.map do |subject|%>
            <td><%= student_mark(student.id,subject.id)%></td>
          <%end%>
          <td><%= student.total%></td>
          <td><%= student.rank%></td>
          <td><%= link_to 'Show', student %></td>
          <td><%= link_to 'Edit', edit_student_path(student) %></td>
          <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%else%>  
          <td><%= student.student_marks.find_by_subject_id(subject_id).mark rescue ""%></td>
        <%end%>  
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%if check_admin(current_user.role_id)%><%= link_to 'New Student', new_student_path %><%end%>

app/views/students/mark_form.html.erb
<h1>Students Mark</h1><br>
<h2>Subject Name:  <%= @subject.name%></h2>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mark</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= form_for @student_mark,url: {contoller: "students",action: "student_mark_create"} do |form|%>
      <% @students.each do |student| %>
        <tr>
          <%= hidden_field_tag "student_mark[id][]" ,student_mark_id(student.id,@subject.id) %>
          <%= hidden_field_tag "student_mark[student_id][]" ,student.id %>
          <td><%= student.name %></td>
          <td><%= number_field_tag "student_mark[mark][]",student_mark(student.id,@subject.id),required: true%></td>
        </tr>
      <% end %>
      <tr><td><%= form.submit "Assign"%></td></tr>
    <%end%>
  </tbody>
</table>

<br>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Student ID:</strong>
  <%= @student.student_id %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>