config/routes.rb
Rails.application.routes.draw do

  resources :subjects  do
    get :subject_teacher_list,on: :collection
    get :assign_teachers,on: :collection
    post :create_teachers_subject,on: :collection
  end	
  resources :students do 
    post :student_mark_create,on: :collection
    get :mark_form, on: :collection
  end  
  root :to => "sessions#new"
  resources :users
  resources :sessions, only: [:new, :create, :destroy] 
  get "login", to: 'sessions#new', as: 'login'
  get "logout", to: 'sessions#destroy', as: 'logout'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subject.rb
class Subject < ApplicationRecord
	has_many :student_marks
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def subject_teacher_list
   @user_subjects = UserSubject.all
  end  

  def assign_teachers
    @user_subject = UserSubject.new
    @teachers = User.where(role_id: Role.find_by_name("Teacher"))
    @subjects = Subject.all
  end

  def create_teachers_subject
    @user_subject = UserSubject.new(user_subject_params)

    respond_to do |format|
      if @user_subject.save
        format.html { redirect_to subject_teacher_list_subjects_url , notice: 'Successfully Assigned subject to Teacher.' }
      else
        format.html { redirect_to subject_teacher_list_subjects_url , notice: 'Already Assigned this Subject' }
      end
    end
  end  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subject_params
      params.require(:subject).permit(:name, :code, :status)
    end

    def user_subject_params
      params.require(:user_subject).permit(:user_id, :subject_id)
    end

end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_with(model: subject, local: true) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :subject_name %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code, id: :subject_code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subjects/assign_teachers.html.erb
<%= form_for @user_subject, url: {controller: "subjects",action: "create_teachers_subject"} do |form| %>
 

  <div class="field">
    <%= form.label :subject_id ,"Subject" %>
    <%= form.collection_select :subject_id, @subjects, :id, :name ,prompt: "Select Subject"%>
  </div>

  <div class="field">
    <%= form.label :user_id, "Teacher" %>
    <%= form.collection_select :user_id, @teachers, :id, :name,prompt: "Select Teacher" %>
  </div>

  

  <div class="actions">
    <%= form.submit "Create" %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subjects</h1>

<table border="2">
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.name %></td>
        <td><%= subject.code %></td>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subject.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @subject.code %>
</p>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/subject_teacher_list.html.erb
<p id="notice"><%= notice %></p>

<h1>Teachers Subjects</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Tecaher</th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @user_subjects.each do |user_subject| %>
      <tr>
        <td><%= user_subject.subject.name %></td>
        <td><%= user_subject.user.name %></td>
        <!-- <td><%#= link_to 'Show', subject %></td>
        <td><%#= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%#= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Subject', new_subject_path %>