config/routes.rb
Rails.application.routes.draw do

  resources :subjects  do
    get :subject_teacher_list,on: :collection
    get :assign_teachers,on: :collection
    post :create_teachers_subject,on: :collection
  end	
  resources :students do 
    post :student_mark_create,on: :collection
    get :mark_form, on: :collection
  end  
  root :to => "sessions#new"
  resources :users
  resources :sessions, only: [:new, :create, :destroy] 
  get "login", to: 'sessions#new', as: 'login'
  get "logout", to: 'sessions#destroy', as: 'logout'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentMarkList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <%if check_admin(current_user.role_id)%>
        <%= link_to "Students", students_path()%>
        <%= link_to "Subjects", subjects_path()%>
        <%= link_to "Teachers", users_path()%>
        <%= link_to "Assign Subject To Teachers", assign_teachers_subjects_path()%>
      <%elsif current_user.user_subject.present?  %>  
        <%= link_to "Add Marks", mark_form_students_path()%>
      <%end%>
    <%end%>
  	<div class="row" style="float: right;">
			<% if current_user %>
			  Logged in as <%= current_user.email %>.
			  <%= link_to "Log Out", logout_path %>
			<% else %>
			  <%= link_to "Log In", login_path %>
			<% end %>
	  </div>
    <%= yield %>
  </body>
</html>